// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
package IngDelSw.nicoli.model;

import jakarta.persistence.*;

/**
 * 
 */
@Entity
@Table (name = "localization_view_photos")
public class LocalizationViewPhotos {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	@ManyToOne
	@JoinColumn(name = "localization_view_id", nullable = false)
	private LocalizationView localizationView;

	@ManyToOne
	@JoinColumn(name = "photo_id", nullable = false)
	private Photo photo;

	public LocalizationViewPhotos() {
	}

	/**
	 * GETTERS AND SETTERS
	 */

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public LocalizationView getLocalizationView() {
		return localizationView;
	}

	public void setLocalizationView(LocalizationView localizationView) {
		this.localizationView = localizationView;
	}

	public Photo getPhoto() {
		return photo;
	}

	public void setPhoto(Photo photo) {
		this.photo = photo;
	}
}
