// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
package IngDelSw.nicoli.model;

import jakarta.persistence.*;

import java.util.Set;

/**
 * 
 */
@Entity
@Table(name = "localization_view")
public class LocalizationView {

	public LocalizationView() {

	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	/**
	 * 
	 */
	@Column(name = "localization_id")
	private Integer localizationId;

	/**
	 * 
	 */
	@Column(name = "name")
	private String name;
	/**
	 * 
	 */
	@Column(name = "priority")
	private Integer priority;


	/**
	 * 
	 */
	public void localizations() {
	}

	public Integer getLocalizationId() {
		return localizationId;
	}

	public void setLocalizationId(Integer localizationId) {
		this.localizationId = localizationId;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getPriority() {
		return priority;
	}

	public void setPriority(Integer order) {
		this.priority = order;
	}
	
}
