// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
package IngDelSw.nicoli.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;

/**
 * 
 */
@Entity
@Table(name = "photos")
@JsonIgnoreProperties({"visit"}) // Ignora i campi che potrebbero causare il ciclo infinito
public class Photo {
	/**
	 * 
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	/**
	 * 
	 */
	@ManyToOne
	@JoinColumn(name = "visit_id", nullable = false)
	private Visit visit;
	/**
	 * 
	 */
	@Column(name = "image")
	private String image;
	/**
	 * 
	 */
	@ManyToOne
	@JoinColumn(name = "localization_view_id", nullable = false)
	private LocalizationView localizationView;

	public Photo() {
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Visit getVisit() {
		return visit;
	}

	public void setVisit(Visit visit) {
		this.visit = visit;
	}

	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public LocalizationView getLocalizationView() {
		return localizationView;
	}

	public void setLocalizationView(LocalizationView localizationView) {
		this.localizationView = localizationView;
	}
}
